name: Lint

on:
  pull_request_target:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup jdk 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: add permission to gradlew
        run: chmod +x ./gradlew
        shell: bash

      - name: test
        run: ./gradlew ktlintCheck
        shell: bash
